---
title: "Physical activity as an effect modificator of lifestyle factors on small vessel deisease burden"
format:
  poster-typst: 
    size: "18x24"
    poster-authors: "A. Smith, B. Jones, C. Brown, D. Miller"
    departments: "Department of Computer Science"
    institution-logo: "images/dsc-logo-black.png"
    footer-text: "ESOC 2024"
    footer-url: "https://posit.co/conference/"
    footer-emails: "andrlr@rm.dk"
    footer-color: "ebcfb2"
    keywords: ["Stroke", "Physical Activity", "Small vessel disease"]
    num_columns: "2"
    univ_logo_scale: "50"
    title_font_size: "34"
    authors_font_size: "20"
    univ_logo_column_size: "4"
    title_column_size: "10"
    footer_url_font_size: "15"
    footer_text_font_size: "24"
---

## **Background and aims** 

Physical activity (PA) may reduce the development of small vessel disease (SVD). The effect of physical activity and more classical vascular risk factors such as hypertension and diabetes in the development of SVD is debated, however. We aim to investigate the effect modification of physical activity on traditional vascular risk factors and the burden of small vessel disease among acute ischemic stroke patients.

## **Methods**

We have pooled patients from two clinical trials on acute ischemic stroke treatment. The main outcome is an ordinal scale score of quantified MR biomarkers of small vessel disease (SVD) burden based on visually assessed acute stroke scans (T2\* or SWI and FLAIR sequences). Biomarkers includes microbleeds, old lacunar infarcts, superficial siderosis, white matter hyperintensities and atrophy. Covariates includes age, sex, pre-stroke physical activity, diabetes, hypertension, atrial fibrillation and previous cardiovascular diseases. Pre-stroke PA was assessed with a questionnaire on inclusion within a few days after stroke onset. Data will be analyzed using bivariate and multivariate linear regression analysis. 

## **Results** 

We expect to include a total of around 1000 adult patients admitted to the comprehensive stroke centre at Aarhus University Hospital between 2013-2022. Preliminary results will be presented at ESOC 2024. 

```{dot}
//| label: fig-flowchart
//| fig-cap: "Flowchart of subject included for analysis"
//| file: images/flow.dot
```

## **Conclusions** 

Physical activity may be an important factor in modifying the risk of SVD development in stroke patients.


