project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default

execute:
  freeze: true
  eval: true
  echo: false
  message: false
  
authors:
  - name: Andreas Gammelgaard Damsbo
    orcid: 0000-0002-7559-1154
    email: andrlr@rm.dk
    url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
    affiliations:
      - ref: dsc
      - ref: dcm
      - ref: sdc
    corresponding: true
    roles:
      - writing
      - analysing
      - data collection
  - name: Rolf Ankerlund Blauenfeldt
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Sigrid Breinholt Vestergaard
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Niels Lech Pedersen
    affiliations:
      - ref: dcm
    roles:
      - data collection
  - name: Kim Morgenstjerne Østerskov
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Mette Foldager Hindsholm
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Arzu Bilgin-Freiert
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Claus Ziegler Simonsen
    affiliations:
      - ref: dsc
      - ref: dcm
    roles:
      - data collection
  - name: Rikke Beese Dalby
    affiliations:
      - ref: sduh
      - ref: dcm
    roles:
      - data collection
  - name: Grethe Andersen
    affiliations:
      - ref: dsc
      - ref: dcm
  - name: Janne Kaergaard Mortensen
    affiliations:
      - ref: dsc
      - ref: dcm
affiliations:
  - id: dsc
    name: Danish Stroke Centre
    department: Aarhus University Hospital
    city: Aarhus
    country: Denmark
    url: https://www.en.auh.dk/departments/danish-stroke-centre/
  - id: dcm
    name: Department of Clinical Medicine
    department: Aarhus University
    city: Aarhus
    country: Denmark
    url: https://clin.au.dk/
  - id: sdc
    name: Steno Diabetes Centre
    department: Aarhus University Hospital
    city: Aarhus
    country: Denmark
    url: https://www.stenoaarhus.dk/
  - id: sduh
    name: South Denmark University Hospital
    department: Radiology
    city: Esbjerg
    country: Denmark
    url: https://regionsyddanmark.dk/fagfolk/forskning/syddansk-universitetshospital



