---
title: SVD analysis plan
subtitle: |
  Small vessel disease burden in acute ischemic stroke - the role of physical activity and vascular risk factors
date: last-modified
formats:
  - docx
  - html
bibliography: references.bib
reference-location: margin
tbl-cap-location: margin
fig-cap-location: margin
# citation-location: margin
filters:
  - acronyms
acronyms:
  fromfile: ./acronyms_list.yml
  include_unused: false
  insert_links: false
  loa_title: "Abbrevations"
  insert_loa: false
  on_duplicate: keep
  non_existing: error
---

# Introduction

\acr{PA} may reduce the development of \acr{SVD}. The effect of \acr{PA} and more classical \acr{CVRF} such as hypertension and diabetes in the development of \acr{SVD} is debated, however.

We aim to investigate if \acr{PA} can counter the effects of hypertension, diabetes and other traditional \acr{CVRF} on the development of cerebral small vessel disease among ischemic stroke patients.

# Methods

## Study population

This study is a pooled, post-hoc, cross-sectional study on \acr{AIS} patients pooled from two large randomized, clinical trials, the \acr{TALOS} and the \acr{RESIST} trials.[@kraglund2018; @blauenfeldt2023]

The \acr{TALOS} trial included first-time stroke within seven days after stroke onset and randomized to citalopram or placebo treatment. More detailed inclusion criteria has already been published.[@kraglund2018]

In the \acr{RESIST} trial, patients presenting with a prehospital putative acute stroke within four hours of symptom onset were randomized in the ambulance to ischemic preconditioning treatment or sham.[@blauenfeldt2023]

In this current trial, we included patients with a final diagnosis of \acr{AIS} included at Aarhus University Hospital, with available, acute magnetic resonance imaging and prestroke \acr{PA} assessment.

## MRI sequences and feature annotation

Obtained \acr{MRI} sequences are from the initial acute stroke protocol scan at the time of stroke admission. These include FLAIR as well as T2\* or SWI sequences depending on the time of inclusion. All with a magnetic field strength of 3 T.[^1]

[^1]: Other metadata can be exported from MR database.

The \acr{MRI} sequences were evaluated by two independent assessors. On disagreement, consensus scoring was performed by a third assessor.

## Prestroke data

Clinical data include age and sex.

Prestroke data is retrieved from the Danish Stroke Registry. Variables included are hypertension, diabetes, prior \acr{AIS}, prior \acr{TIA} and regular smoking, and are all binary (yes/no).[^2]

[^2]: Other factors include cohabitation, atrial fibrilation, myocardial infarction and alcohol consumption. They are left out to keep the focus, but can be included like the already listed risk factors in the suplementary material as "other risk factors".

## Physical activity

Prestroke \acr{PA} was assessed using the \acr{PASE} questionnaire on trial enrolment. The \acr{PASE} is a validated 12-item self-assessed questionnaire on overall \acr{PA} including work, leisure time, household, and sports activities during the past 7 days. The score ranges from 0 to 793, with a higher score indicating a higher level of \acr{PA}. The \acr{PASE} questionnaire was completed by the patient or next of kin, and possibly with the assistance of study personnel.

## Statistics

Evaluation of effect modification[@corraini2017] of \acr{PA} on \acr{CVRF}s (e.g. diabetes, hypertension, smoking, previous ischemic cerebrovascular event (\acr{AIS} and/or \acr{TIA})) and the burden of \acr{SVD} will be performed using \acr{OLR}.

Separate \acr{OLR} models with individual \acr{CVRF} as the independent variable and \acr{SVD} score as the dependent variable without and with \acr{PA} quartiles will be created. All analysis will be adjusted for age and sex. In @tbl-main the combined analyses for the simple \acr{SVD} score is showed.

The outcome \acr{SVD} score will be evaluated using a full scale and a simplified scale, as well as each sub score. In @tbl-other an overview of the other analyses, that will be performed.

### Analyses

Below is listed the main analyses to give an overview.

```{r}
#| label: tbl-main
#| tbl-cap: "Main analyses reference table"
#| echo: false
c("diabetes","hypertension","smoking","ischemic event") |> 
  purrr::imap(function(.x,.i){
    tibble::tibble(paste0("0",.i,c("a","b")),
                   "\\acr{OLR}",
                   "\\acr{SVD} score (0-4)",
                   paste(stringr::str_to_sentence(.x), "(yes/no)"),
                   c("Age, sex","Age, sex, \\acr{PA} quartile"))|> 
      setNames(c("Reference",
                   "Model",
                   "Dependent variable",
                   "Independent variables",
                   "Other adjustment"))
  }) |> 
  dplyr::bind_rows() |> 
  knitr::kable()

```

Below is listed the sub analysis on sub scores and the full SVD score.

|               |           |                           |
|---------------|-----------|---------------------------|
| **Reference** | **Model** | **Dependent variable**    |
| **11-14**     | \acr{OLR} | Microbleeds (0,1-10,\>10) |
| **21-24**     | \acr{OLR} | Lacunes (0,1,\>1)         |
| **31-34**     | \acr{OLR} | \acr{WMH} (0,1,2,3)       |
| **41-44**     | \acr{OLR} | Atrophy (0,1,2,3)         |
| **51-54**     | \acr{OLR} | \acr{SVD} score (0-14)    |

: Sub-score analyses {#tbl-other .striped .hover}

All planned tables and figures to be included.

|                          |                                                                                                                  |
|-------------------------|-----------------------------------------------|
| **Reference**            | **Description**                                                                                                  |
| **Table 1**              | Baseline characteristics.                                                                                        |
| **Table 2**              | Merged tables with primary analyses of simplified \acr{SVD} score for each \acr{CVRF} with and without \acr{PA}. |
| **Figure 1**              | Odds ratios from the main OLR analyses.                                                                         |
| **Table 3**              | Merged table of each \acr{SVD} sub score as outcome for each \acr{CVRF}.                                         |
| **Supplementary tables** | Merged tables with analyses of full \acr{SVD} score.                                                             |

: Planned tables and figures {#tbl-tables .striped .hover}

<!-- # DAGs -->

<!-- ```{r} -->
<!-- #| label: fig-dags -->
<!-- #| fig-cap: "DAGs to consider" -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| fig-align: center -->
<!-- #| out-width: 100% -->
<!-- source(here::here("notebooks/_dags.R")) -->
<!-- p_dag -->
<!-- ``` -->


# References {.unnumbered}

::: {#refs}
:::
